### ISSUE TITLE
Crash when creating GDPR dialog in Unity

### ISSUE THREAD

**Issue by martino2k6** [loopme/android-united-sdk#39]
When using your Android SDK 6.3.12 under Unity 5.6.5 I'm getting the following crash when trying to load an ad through:
```
LoopMeInterstitial ad = LoopMeInterstitial.getInstance(appKey, activity);
ad.setAutoLoading(false);
ad.load();
```

And the stack trace:
```
    java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.support.v7.app.AppCompatDelegateImplV9.createSubDecor(AppCompatDelegateImplV9.java:354)
        at android.support.v7.app.AppCompatDelegateImplV9.ensureSubDecor(AppCompatDelegateImplV9.java:323)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
        at android.support.v7.app.AppCompatDialog.setContentView(AppCompatDialog.java:83)
        at android.support.v7.app.AlertController.installContent(AlertController.java:226)
        at android.support.v7.app.AlertDialog.onCreate(AlertDialog.java:260)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:403)
        at android.app.Dialog.show(Dialog.java:302)
        at com.loopme.gdpr.GdprDialog.showDialog(GdprDialog.java:64)
        at com.loopme.gdpr.GdprDialog.onPageLoaded(GdprDialog.java:59)
        at com.loopme.gdpr.GdprWebView.onPageLoaded(GdprWebView.java:151)
        at com.loopme.gdpr.GdprWebView.access$100(GdprWebView.java:28)
        at com.loopme.gdpr.GdprWebView$1.onPageFinished(GdprWebView.java:94)
        at xf.c(PG:251)
        at aeb.handleMessage(PG:72)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
```

Any help with this would be greatly appreciated. Thank you.

**Comment by bregulich** [comment]
You need to use a Theme.AppCompat theme (or descendant) with this activity.
