### ISSUE TITLE
LoopMe android sdk 6.1.6 GDPR Dialog Crash

### ISSUE THREAD

**Issue by Snehahshis** [loopme/android-united-sdk#41]
GDPR consent dialog appears automatically and multiple times, one above another. 
Also there has following crashes 

1. On Dialog show
Fatal Exception: android.view.WindowManager$BadTokenException: Unable to add window -- token android.os.BinderProxy@3257fbc is not valid; is your activity running?
       at android.view.ViewRootImpl.setView(ViewRootImpl.java:975)
       at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
       at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:100)
       at android.app.Dialog.show(Dialog.java:420)
       at com.loopme.gdpr.GdprDialog.showDialog(GdprDialog.java:64)
       at com.loopme.gdpr.GdprDialog.onPageLoaded(GdprDialog.java:59)
       at com.loopme.gdpr.GdprWebView.onPageLoaded(GdprWebView.java:151)
       at com.loopme.gdpr.GdprWebView.access$100(GdprWebView.java:28)
       at com.loopme.gdpr.GdprWebView$1.onPageFinished(GdprWebView.java:94)
       at xq.c(SourceFile:228)
       at alW.handleMessage(SourceFile:72)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6944)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

** need to check isFinishing() on activity context before show dialog

2. On Dialog dismiss
Fatal Exception: java.lang.IllegalArgumentException: View=com.android.internal.policy.PhoneWindow$DecorView{7881653 V.E...... R.....I. 0,0-0,0} not attached to window manager
       at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:451)
       at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:375)
       at android.view.WindowManagerImpl.removeViewImmediate(WindowManagerImpl.java:116)
       at android.app.Dialog.dismissDialog(Dialog.java:385)
       at android.app.Dialog.dismiss(Dialog.java:364)
       at com.loopme.gdpr.GdprDialog.dismissDialog(GdprDialog.java:77)
       at com.loopme.gdpr.GdprDialog.onClose(GdprDialog.java:72)
       at com.loopme.gdpr.GdprWebView.onClose(GdprWebView.java:158)
       at com.loopme.gdpr.GdprWebView.access$300(GdprWebView.java:28)
       at com.loopme.gdpr.GdprWebView$1.shouldOverrideUrlLoading(GdprWebView.java:101)
       at jU.b(PG:83)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:172)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:328)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:5728)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

** need to check isFinishing() on activity context before dismiss the dialog

**Comment by bkorda** [comment]
Hello Snehahshis, thank you for feedback. What type of integration do you use?

**Comment by bregulich** [comment]
Fixed in v7.0.0.
